name: push

on:
  push:
    branches:
      - master

jobs:
  push_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        registry: [ghcr.io, public.ecr.aws]
    env:
      GH_USER: "aqua-bot"

    steps:
      - uses: actions/checkout@v3

      - name: Set TEST_IMAGE variable for Makefile
        run: echo "TEST_IMAGE=${{ matrix.registry }}/${{ github.repository_owner }}/trivy-test-images" >> $GITHUB_ENV

      - name: Login to GHCR
        if: matrix.registry == 'ghcr.io'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.GH_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to ECR Public
        if: matrix.registry == 'public.ecr.aws'
        uses: docker/login-action@v3
        with:
          registry: public.ecr.aws
          username: ${{ secrets.ECR_ACCESS_KEY_ID }}
          password: ${{ secrets.ECR_SECRET_ACCESS_KEY }}

      - name: Setup Go
        uses: actions/setup-go@v4

      - name: Get changed files
        id: changed-files-yaml
        uses: tj-actions/changed-files@v37
        with:
          files_yaml: |
            busybox:
              - 'busybox-with-lockfile/**'
            containerd:
              - 'containerd/**'
            spring4shell:
              - 'spring4shell/**'
            crane-images:
              - copy-images.sh

      - name: Push `busybox-with-lockfile` image
        if: steps.changed-files-yaml.outputs.busybox_any_changed == 'true'
        run: make build-busybox

      - name: Push `containerd` image
        if: steps.changed-files-yaml.outputs.containerd_any_changed == 'true'
        run: make build-containerd

      - name: Push `spring4shell` image
        if: steps.changed-files-yaml.outputs.spring4shell_any_changed == 'true'
        run: make build-spring4shell

      - name: Copy images
        if: steps.changed-files-yaml.outputs.crane-images_any_changed == 'true'
        run: make copy-images